/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        DirCalculator classUnderTest = new DirCalculator();
        assertNotNull(classUnderTest.askUserForAPath(), "app should have an input");
    }
    
    @Test public void doesItExist(){
    	DirCalculator app = new DirCalculator();
    	assertEquals(app.checkIfPathExists("Some path"), false,"I don't have such directory");
    }
    
    @Test public void ItExistTrue(){
    	DirCalculator app = new DirCalculator();
    	assertEquals(app.checkIfPathExists(System.getProperty("user.home")), true,"I have such directory");
    }
    
    @Test public void WillCountFiles(){
    	DirCalculator app=new DirCalculator();
    	assertEquals(app.CountFilesInDir("C:\\EPAM"), 4, "Counted files in path correct");
    }    
}